import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Optional
from datetime import datetime, timezone
import json

# For now, we will use a mock service. The user can add real SMTP keys in .env
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
FROM_EMAIL = os.getenv("FROM_EMAIL", "notifications@edunovas.ai")

class NotificationService:
    def send_job_notification(self, user_email: str, job_matches: List[Dict]):
        """
        Sends an email notification with new job matches.
        """
        if not SMTP_USER or not SMTP_PASS:
            print(f"⚠️ Mock Email to {user_email}: Found {len(job_matches)} high-suitability jobs!")
            for job in job_matches:
                print(f" - {job['title']} at {job['source']} ({job['suitability_score']}% match)")
            return True

        try:
            msg = MIMEMultipart('alternative')
            msg['From'] = FROM_EMAIL
            msg['To'] = user_email
            msg['Subject'] = f"🚀 {len(job_matches)} New High-Suitability Jobs for You!"

            # Professional HTML Template
            html_body = f"""
            <html>
                <body style="font-family: Arial, sans-serif; color: #333333; line-height: 1.6; max-width: 600px; margin: 0 auto; padding: 20px;">
                    <div style="text-align: center; margin-bottom: 30px;">
                        <h2 style="color: #0064FF; margin: 0;">Edunovas AI Job Agent</h2>
                        <p style="color: #666666; font-size: 14px; margin-top: 5px;">Your Daily Match Assessment</p>
                    </div>
                    
                    <p style="font-size: 16px;">Hello,</p>
                    <p style="font-size: 16px;">Our proactive AI Job Agent has identified <strong>{len(job_matches)}</strong> new opportunities that align closely with your verified skills and resume.</p>
                    
                    <div style="margin-top: 25px;">
            """
            
            for index, job in enumerate(job_matches, 1):
                score_color = "#10B981" if job['suitability_score'] >= 90 else "#3B82F6"
                html_body += f"""
                        <div style="border: 1px solid #E5E7EB; border-radius: 8px; padding: 15px; margin-bottom: 20px; background-color: #F9FAFB;">
                            <h3 style="margin: 0 0 10px 0; color: #111827; font-size: 18px;">{index}. {job['title']}</h3>
                            <p style="margin: 5px 0;"><strong>Source/Company:</strong> {job['source']}</p>
                            <p style="margin: 5px 0;"><strong>Suitability Match:</strong> <span style="color: {score_color}; font-weight: bold;">{job['suitability_score']}%</span></p>
                            <div style="margin-top: 15px;">
                                <a href="{job['link']}" style="background-color: #0064FF; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; font-weight: bold; font-size: 14px; display: inline-block;">Apply Now</a>
                            </div>
                        </div>
                """
                
            html_body += """
                    </div>
                    
                    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #E5E7EB; text-align: center; color: #888888; font-size: 12px;">
                        <p>Keep learning and building!<br><strong>Team Edunovas</strong></p>
                        <p>This is an automated message generated by the Edunovas AI Job Agent. Please do not reply directly to this email.</p>
                    </div>
                </body>
            </html>
            """
            
            # Plain text fallback
            text_body = f"Hello,\n\nOur AI Job Agent found {len(job_matches)} new roles that match your profile!\n\n"
            for job in job_matches:
                text_body += f"- {job['title']} at {job['source']} ({job['suitability_score']}% match)\n  Link: {job['link']}\n\n"
            text_body += "Team Edunovas"

            msg.attach(MIMEText(text_body, 'plain'))
            msg.attach(MIMEText(html_body, 'html'))

            server = smtplib.SMTP(SMTP_HOST, SMTP_PORT)
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.send_message(msg)
            server.quit()
            return True
        except Exception as e:
            print(f"Failed to send email: {e}")
            return False

    def record_match(self, supabase, user_id: str, job_link: str, score: int):
        """Records a match so we don't notify the same job twice."""
        try:
            supabase.table('job_matches').insert({
                'user_id': user_id,
                'job_link': job_link,
                'match_score': score,
                'created_at': datetime.now(timezone.utc).isoformat()
            }).execute()
        except Exception as e:
            print(f"Match recording error: {e}")

    def was_notified(self, supabase, user_id: str, job_link: str) -> bool:
        """Checks if the user was already notified about this specific job."""
        try:
            res = supabase.table('job_matches').select('id').eq('user_id', user_id).eq('job_link', job_link).execute()
            return len(res.data) > 0
        except:
            return False

notification_service = NotificationService()
